sudo: false
language: python
install: pip install tox
matrix:
  include:
  - python: "2.7"
    env: TOX_ENV=py27
  - python: "3.8"
    env: TOX_ENV=static
  - python: "3.8"
    env: TOX_ENV=cov-travis DEPLOY=1
  - python: "3.8"
    env: TOX_ENV=docs
script: tox -e $TOX_ENV
after_success:
- test $TOX_ENV = docs && scripts/push-docs

deploy:
  provider: pypi
  user: __token__
  password:
    secure: nFXMaMJRGtHhPKikMlFTf435iVGNTXn+Z2lYIlNY8VLR3Aa/ggJAI0fp/805ka4cjaynbvAIK6OUj6H7GmxkIwc371BIaAdBRYD5JY1c09/1DQV1LVfkEMtuJfMqtDzCbcazKW23MdFXuuqL5Dg+vGEBfA4/Jm+ybm4ftBfa1GDbl7BGCsVbCXhdRDHooZYET9qYhK/UKkjpBMMwT0lu23OVFtwYLnROu9rbyVIpWpz/iG74/DWbFPKZDvTFjx12E6Rcj0iX3BZUl1sdBhzL9CdGV6iZ4swyLdge3MeXZwNq1c56Lep8UB5rAgGLQJPgDOXSlpRtUGMvrOd09rNPV7J9/ativ38f2mfdJOChEejGdx9Qz+v7+yH0uPDZhig2enQ0dLB+2CZtFvYqeyT2WpAVPKYrjvBo1IlqmMmc4HZbE7ABzpcji6QeKuxl5evtSVXiF9qWSqOO1+7SacZ/OwfEY/CVWISuvuB+HkNvzcJqftUXl60IRRu8Ar2hPVjk47bTrum0QhL5gILVPcV7Zb2818BLg+b+CqfUZlhKZdGmCmEiXrZifOPyvIUsFRHWA6bmGACYVeXMKWCC4570SC6TBYq4ns/kf0idqiRXDnsC+w7gUGaSAD+ShdrhSOmKXD1jx+P2oDlrwpOTLATEaJdXRv6G5S5vmTZK2I953WY=
  on:
    tags: true
    condition: $DEPLOY = 1
  skip_existing: true
